In [71]:
import random,pylab,numpy as np,time
x = random.sample(range(20),10)
y = [ 90 * i + random.random()*10 for i in x ]
x = np.array(x)
y = np.array(y)
N = len(x)

In [72]:

x,y

(array([13, 15,  3,  1,  6, 16, 10, 18,  4,  9]),
 array([1178.4450585 , 1353.23167489,  272.62563304,   96.88590702,
         545.05161438, 1440.82394255,  906.58195416, 1629.41851756,
         361.48415004,  815.17430576]))

In [20]:
def mse(predictions,y):
  res = 0 
  for i,j in zip(predictions,y):
    res += (i-j)**2
  return res/len(y)

In [25]:
def MSE(predictions,y):
  #predictions and y are both arrays
  return ((predictions - y )**2).sum()/len(y)

In [40]:
def draft(x,y,m =1,c=0.1,learning_rate = 0.001):
  for i in range(1000):
    predictions = [ m * i + c for i in x]
    dc = -2/N * sum(  [ (i-j) for i,j in zip(y,predictions)])
    dm = -2/N * sum(  [ (i-j)*k for i,j,k in zip(y,predictions,x)])
    c = c - learning_rate*dc
    m = m - learning_rate * dm
  return m,c 


In [73]:

draft(x,y),

((89.95923934880281, 5.827518620048117),)

In [55]:

def getdata(filename):
  distances,forces = [],[]
  file = open(filename,'r')
  file.readline()
  for line in file:
    d,m = line.split(' ')
    distances.append(float(d))
    forces.append(9.81 * float(m))
  file.close()
  return forces,distances

In [74]:
# x,y = getdata('springData.txt')
x = pylab.array(x)
y = pylab.array(y)

In [75]:
pylab.polyfit(x,y,1)

array([90.10177573,  4.00540637])

In [69]:
def gradient_descent(x,y,m =0,c=0,learning_rate = 0.001):
  N = len(x)
  tag = 0
  for i in range(100000):
    predictions =  m * x + c
    tag += 1
    dc = -2/N *  (y-predictions).sum() * (learning_rate)
    dm =-2/N * ((y-predictions)*x).sum() * (learning_rate)
    if (dc > -0.0000001 and dc <0.0000001 ) and (dm > -0.0000001 and dm <0.0000001 ):
      break 
    c = c - dc
    m = m - dm
    #assume that it can  have  both negative and positive values  
  print(tag)
  return m,c


In [76]:
gradient_descent(x,y)

18784


(90.10176050876012, 4.005600930513724)

In [77]:
import time
t = time.time()
draft(x,y)
print(time.time()-t)
s = time.time()
pylab.polyfit(x,y,1)
print(time.time()-s)
j = time.time()
gradient_descent(x,y)
time.time()-j

0.016381025314331055
0.0003521442413330078
18784


0.20021581649780273